-- Drop and recreate Likes table

DROP TABLE IF EXISTS likes
CASCADE;

CREATE TABLE likes
(
  id SERIAL NOT NULL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ,
  resource_id INTEGER NOT NULL REFERENCES resources(id) ON DELETE CASCADE,
  created TIMESTAMP
  WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP
  WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
  --  emoji_id INTEGER NOT NULL DEFAULT 0
);
